### ISSUE TITLE
Unable to make API call /public/alertNotificationRules POST work to define a new notification rule - any advice is appreciated.

### ISSUE THREAD

**Issue by amlucent** [cohesity/ansible-collection#3] opened 2022-05-19 19:12 UTC
So I am trying to automate creating a new alert notification rule via ansible url module playbook (below), but I cant get this to work via curl actually either.  I was just wondering if you have this working under any circumstances?  I’ve been battling this for over a week.  Perhaps is the developer guide info for this call incorrect?  Or maybe I have just been staring at the problem for too long..

I am in need of this to work for 6.5.1f but Im also looking ahead to 6.6 api instructions as well.  Seemingly my json payload is simply not what the API was expecting and it fails and when it fails It seemingly erases any manually entered notification rules entered from the web gui and gives me a response code of 200.  I have tried doing it exactly as the API documentation suggests with all the options included in the body json and only received a different failure code.  The documentation claims I should see a response code of 201 if successful.    

Can you provide a working json example (via curl is fine)?  What I create from the blow link still fails.

https://developer.cohesity.com/apidocs/660x/#/http/api-endpoints/alerts/create-notification-rule

[set-alerts.yml.txt](https://github.com/cohesity/ansible-collection/files/8733597/set-alerts.yml.txt)

**Comment by naveena-maplelabs** [comment] 2022-05-30 10:31
@amlucent Can you please try with the following payload,
```
{
   "emailDeliveryTargets":[],
    "ruleName":"devRule",
    "categories":["kBackupRestore"],
    "severities":["kCritical"],
    "alertTypeList":[10006]
}
```

**Comment by naveena-maplelabs** [comment] 2022-05-31 03:36
Sample payload with **emailDeliveryTargets**
```
[
  {
    "ruleId": 1653967923,
    "ruleName": "test",
    "categories": [
      "kAuditLog",
      "kArchivalRestore"
    ],
    "severities": [
      "kCritical"
    ],
    "emailDeliveryTargets": [
      {
        "emailAddress": "naveena.maplelabs@cohesity.com",
        "locale": "en-us",
        "recipientType": "kTo"
      }
    ],
    "snmpEnabled": true
  }
]
```
@amlucent, I m closing the issue, please feel free to re-open this if the issue is not resolved.

**Closed by naveena-maplelabs** 2022-05-31 03:36 UTC

**Comment by amlucent** [comment] 2022-05-31 21:50
recipientType in emailDeliveryTargets, according to the API docs I linked, should be an integer value.  Seems like the documentation is incorrect?

**Comment by naveena-maplelabs** [comment] 2022-06-01 03:19
Were you able to create new alert notification rule with the payload provided?

**Comment by amlucent** [comment] 2022-06-03 18:55
yes I was able to get this working well for both 6.5 and 6.6 via ansible.builtin.uri.  I am still searching for a way to set the SMTP server info and NTP server info of a cohesity cluster via the API if you have any advice on such a thing?

**Comment by naveena-maplelabs** [comment] 2022-06-08 15:53
@amlucent 
You can update the ntpServers using the following API & payload.
**PUT irisservices/api/v1/ntpServers**
`{
  "ntpServers": [
    "ntp server 1",
    "ntp server 2"
  ]
}`

**Comment by naveena-maplelabs** [comment] 2022-06-13 17:40
PUT: 

Request URL: https://cluster_ip/irisservices/api/v1/smtpServer
Request Method: PUT
Status Code: 200 
Request Payload: {server: "smtp.gmail.com", port: 587, username: "test2@gmail.com", disableSmtp: false}   Response: {"server":"smtp.gmail.com","port":587,"username":"test2@gmail.com","disableSmtp":false}
